### ISSUE TITLE
Team Meeting- Jan6

### ISSUE THREAD

**Issue by gauravcusp** [argo-marketplace/LA-LocalGeo-CrossWalk#11]
Agenda for tomorrow's call:

- Discuss this week's progress
- Figure out a way to deal with the shortcomings
- Tasks for next week
@vr00n @lingyielia @xd515 @iuk0162 

# How to submit an issue?

- [x] Have you checked previously open/closed issues to see if your question has already been asked & addressed? 
  - If there is an open issue similar to your issue. Comment on that open issue with additional detail indicating that you too are having the same issue. This allows the project sponsor to prioritize incoming issues.
- [x] Have you provided a clear description of your issue so that the project sponsor is able to answer all your questions with as few back-n-forths as possible?
- [x] (Please acknowledge by checking this box) If a screenshot or visual helps better communicate some complex idea, have you provided one?. `Draw.io` and `lucidchart` are some excellent and quick drawing tools.
- [x] (Please acknowledge by checking this box) When an issue is resolved, please post the steps to resolution or clearly describe the resolution before marking the issue closed. 
   - This will help future `SOLVERS` read through how your issue was solved and may help them solve their issue quicker.
- [x] Have you been kind, courteous, and considerate in your questions? 
- [x] Have you considered using `Stackedit.io`, a handy tool to quickly write in markdown?

**Comment by vr00n** [comment]
Hey guys. Unfortunately I am not feeling very well and will not be able to join the call tomorrow. Can you please discuss amongst yourselves and post meeting minutes here for me to review later. Please keep up the pace and great work!

**Comment by gauravcusp** [comment]
Definitely. Take Care Varun!

**Comment by lingyielia** [comment]
Colleagues @vr00n @iuk0162 @xd515 @gauravcusp

## Meeting discussion
- How to deal with datasets which are not complete geometries of LA County?
 __Option 1__. Leave out these datasets.
 __Option 2__. Make this geo-crosswalk for LA City only.

- Invalid geometries occurred when too many geometries been added in.
- `spatial_overlays` or r-tree. @xd515 performed the r-tree which might be a better method.
- Progress on creating API. Uploading to Carto is quick and direct. [dirt simple postgis http api](https://github.com/tobinbradley/dirt-simple-postgis-http-api) is more sophisticated.
 
## Issues for this week
- Determine the level of geometries (LA county vs. LA city).
- Performace comparison between `spatial_overlays` and r-tree.
- Compare results of geopandas with Arcgis and Qgis.
- Produce the API. (Major goal this week)

**Comment by gauravcusp** [comment]
## Tasks Handled this week 
- Determine the level of geometries (LA county vs. LA city). 
-- [Redirecting to discussion](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/issues/12)
- Performace comparison between spatial_overlays and r-tree. 
-- [Analysis](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/issues/8)
- Compare results of geopandas with Arcgis and Qgis.
-- [Analysis](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/issues/13) 
- Produce the API. (Major goal this week)
-- [Analysis and Discussion](https://github.com/argo-marketplace/LA-LocalGeo-CrossWalk/issues/10)
